#!/usr/bin/env python3
"""
Install selected plugins from the generated wshobson Cursor catalog into .cursor.
"""

from __future__ import annotations

import argparse
import filecmp
import json
import shutil
import sys
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def read_index(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def copy_file_checked(src: Path, dst: Path, force: bool) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() and not force and not filecmp.cmp(src, dst, shallow=False):
        raise RuntimeError(f"destination differs, use --force to overwrite: {dst}")
    shutil.copy2(src, dst)


def copy_dir_checked(src: Path, dst: Path, force: bool) -> None:
    if dst.exists():
        if not force:
            cmp = filecmp.dircmp(src, dst)
            if cmp.left_only or cmp.right_only or cmp.diff_files or cmp.funny_files:
                raise RuntimeError(f"destination differs, use --force to overwrite: {dst}")
        shutil.rmtree(dst)
    shutil.copytree(src, dst)


def selected_plugins(index: dict, args: argparse.Namespace) -> set[str]:
    plugins = index.get("plugins", [])
    all_names = {p.get("name") for p in plugins if isinstance(p, dict) and p.get("supported")}
    if args.all:
        return {name for name in all_names if isinstance(name, str)}

    selected: set[str] = set()
    plugin_filter = set(args.plugin or [])
    category_filter = set(args.category or [])

    for plugin in plugins:
        if not isinstance(plugin, dict) or not plugin.get("supported"):
            continue
        name = str(plugin.get("name", "")).strip()
        category = str(plugin.get("category", "")).strip()
        if name in plugin_filter or category in category_filter:
            selected.add(name)

    unknown_plugins = plugin_filter - all_names
    if unknown_plugins:
        raise RuntimeError(f"unknown plugin(s): {', '.join(sorted(unknown_plugins))}")

    known_categories = {str(p.get("category", "")).strip() for p in plugins if isinstance(p, dict)}
    unknown_categories = category_filter - known_categories
    if unknown_categories:
        raise RuntimeError(f"unknown category(ies): {', '.join(sorted(unknown_categories))}")

    return selected


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--catalog-dir",
        type=Path,
        default=repo_root() / ".cursor" / "_catalog" / "wshobson",
        help="Catalog directory generated by sync_wshobson_to_cursor.py",
    )
    parser.add_argument(
        "--target-cursor-dir",
        type=Path,
        default=repo_root() / ".cursor",
        help="Target .cursor directory for installation",
    )
    parser.add_argument("--all", action="store_true", help="Install all supported plugins")
    parser.add_argument("--plugin", action="append", help="Install a specific plugin (repeatable)")
    parser.add_argument("--category", action="append", help="Install all plugins in a category (repeatable)")
    parser.add_argument("--force", action="store_true", help="Overwrite destination files when content differs")
    args = parser.parse_args()

    if not args.all and not args.plugin and not args.category:
        parser.error("choose one of --all, --plugin, or --category")

    catalog_dir = args.catalog_dir.resolve()
    index_path = catalog_dir / "plugin-index.json"
    if not index_path.is_file():
        print(f"error: plugin index not found: {index_path}", file=sys.stderr)
        return 1

    index = read_index(index_path)
    chosen = selected_plugins(index, args)
    if not chosen:
        print("No plugins matched selection.")
        return 0

    plugin_map = {
        plugin["name"]: plugin
        for plugin in index.get("plugins", [])
        if isinstance(plugin, dict) and plugin.get("supported")
    }

    install_agents: set[str] = set()
    install_skills: set[str] = set()
    install_commands: set[str] = set()
    for plugin_name in sorted(chosen):
        plugin = plugin_map[plugin_name]
        install_agents.update(plugin.get("agents", []))
        install_skills.update(plugin.get("skills", []))
        install_commands.update(plugin.get("commands", []))

    target = args.target_cursor_dir.resolve()
    target_agents = target / "agents"
    target_skills = target / "skills"
    target_agents.mkdir(parents=True, exist_ok=True)
    target_skills.mkdir(parents=True, exist_ok=True)

    copied_agents = 0
    for agent_name in sorted(install_agents):
        source_file = catalog_dir / "agents" / f"{agent_name}.md"
        if not source_file.is_file():
            raise RuntimeError(f"missing catalog agent file: {source_file}")
        copy_file_checked(source_file, target_agents / source_file.name, args.force)
        copied_agents += 1

    copied_skills = 0
    for skill_name in sorted(install_skills):
        source_dir = catalog_dir / "skills" / skill_name
        if not source_dir.is_dir():
            raise RuntimeError(f"missing catalog skill directory: {source_dir}")
        copy_dir_checked(source_dir, target_skills / skill_name, args.force)
        copied_skills += 1

    manifest = {
        "source": "wshobson/agents",
        "catalog_dir": str(catalog_dir),
        "selected_plugins": sorted(chosen),
        "installed_agents": sorted(install_agents),
        "installed_skills": sorted(install_skills),
        "detected_commands": sorted(install_commands),
    }
    (target / ".wshobson-installed.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    print(f"Installed plugins: {len(chosen)}")
    print(f"Agents copied: {copied_agents}")
    print(f"Skills copied: {copied_skills}")
    if install_commands:
        print(
            "Commands detected in selected plugins (not installed in Cursor): "
            + ", ".join(sorted(install_commands))
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
